CREATE TABLE posts (
id 			INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title 		VARCHAR(50),
body 		TEXT,
created 	DATETIME DEFAULT NULL,
modified	DATETIME DEFAULT NULL
);

CREATE TABLE users (
id 			INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username 	VARCHAR(50),
password 	VARCHAR(50),
role 		VARCHAR(20),
created 	DATETIME DEFAULT NULL,
modified 	DATETIME DEFAULT NULL
);